# Generated by Django 2.2.5 on 2020-10-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Second', '0002_auto_20201018_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=40)),
                ('cust_phone', models.IntegerField(max_length=10)),
                ('Salesman_id', models.CharField(max_length=20, unique=True)),
                ('Bike_name', models.CharField(max_length=40)),
                ('Bike_price', models.IntegerField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
